services:
  studio-api:
    container_name: studio-api
    restart: on-failure
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: studio-api
    ports:
      - "3002:3002"
    networks:
      - arandu-network

networks:
  arandu-network:
    name: arandu-network
    driver: bridge